---
title: "ACTI"
subtitle: "The Atlas Career Type Indicator" 
author: "Atlas Research Team"
date: "`r Sys.Date()`"
geometry: a4paper, margin = 1in
output:
  pdf_document:
  # ipsum_pdf:
    # toc: TRUE
    # number_sections: TRUE
    # toc_depth: 4
    # extra_dependencies: ["float"]
    # extra_dependencies: ["flafter"]

header-includes:
   - \usepackage{titlesec}
   - \usepackage{floatrow}
   - \usepackage{physics}
   - \usepackage{mathtools}
   - \floatsetup[figure]{capposition=top}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

\newpage

\titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}

\titlespacing{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}

\setcounter{secnumdepth}{5}

\setcounter{tocdepth}{5}

\tableofcontents

\newpage

# Mathematical Pressupositions

## Notation

Let $\vb{a_u} = (a_1^u, ...,a_m^u)$ be the vector of professional attributes $a_i^u \in [0,100] \ \forall \ i, u$ that characterizes person $u$.

# Defining Career Types

Now, as professional profiles are virtually infinite in their multiplicity, we should make use of dimensionality reduction techniques in order to derive meaningful patterns from the data.

This can be done in a variety of ways --- the most obvious of which is clustering (e.g. K-means, Hierarchical Clustering, etc). However, this approach has the disadvantage of being too closely tied with the data, can be somewhat arbitrary when it comes to define the number of types (i.e. clusters), and lacks theoretical robustness (as types are derived from the data itself, and do not have theoretical underpinnings).

A more interesting methodology for this particular problem is to apply statistical analyses that reduce dimensionality as well as leave open a potentially enormous, albeit finite, number of career types. Whether or not these *theoretical* types actually appear on the population is irrelevant, so long as they are theoretically consistent.

## Truncation

### Insights from Jungian Typology

The analytical psychologist Carl Jung famously wrote of 8 cognitive functions that, when combined, determine 16 personality types (cf. Myers-Briggs' adaptation of Jung's original *Personality Types*).

In these particular theories, personality types are defined by cognitive function stacks, in which certain functions are at the top and, consequently, their opposites, at bottom. In addition, this model does not employ precise measurements for such a definition, only an ordinal classification: one function is primary (or dominant), another is secondary (or auxiliary), yet another is tertiary, and the fourth function (cognitively opposite to the first) is called the repressed function.

### Professional Attribute Classes

A similar approach seems to be very much adequate here. Thus, we can truncate item and/or factor scores so as to reduce data complexity and derive theoretically consistent career types from a vector of professional attributes:

$$
\begin{cases}
a_i^u \in (75,100] \implies \text{Dominant}.
\\ a_i^u \in (50,75] \implies \text{Auxiliary}.\\ a_i^u \in (25,50] \implies \text{Minor}.\\ a_i^u \in [0,25] \implies \text{None}.
\end{cases}
$$

Or a simpler classification to reduce dimensionality even further:

$$
\begin{cases}a_i^u \in (67,100] \implies \text{High Level / Dominant}.\\ a_i^u \in (33,67] \implies \text{Mid Level / Auxiliary}.\\ a_i^u \in (0,33] \implies \text{Low Level / Minor}.\end{cases}
$$

## Item Relevance
